from graph import Graphe2

g = Graphe2()
g.ajouter_arc("Bretagne", "Pays de la Loire")
g.ajouter_arc("Bretagne", "Normandie")
g.ajouter_arc("Provence-Alpes-Côte d'Azur", "Occitanie")
g.ajouter_arc("Provence-Alpes-Côte d'Azur", "Auvergne-Rhône-Alpes")
g.ajouter_arc("Occitanie", "Auvergne-Rhône-Alpes")
g.ajouter_arc("Occitanie", "Nouvelle Aquitaine")
g.ajouter_arc("Grand Est", "Ile-de-France")
g.ajouter_arc("Grand Est", "Hauts-de-France")
g.ajouter_arc("Grand Est", "Bourgogne-Franche-Comté")
g.ajouter_arc("Ile-de-France", "Centre - Val de Loire")
g.ajouter_arc("Ile-de-France", "Bourgogne-Franche-Comté")
g.ajouter_arc("Ile-de-France", "Hauts-de-France")
g.ajouter_arc("Ile-de-France", "Normandie")
g.ajouter_arc("Hauts-de-France", "Normandie")
g.ajouter_arc("Normandie", "Pays de la Loire")
g.ajouter_arc("Normandie", "Centre - Val de Loire")
g.ajouter_arc("Pays de la Loire", "Centre - Val de Loire")
g.ajouter_arc("Pays de la Loire", "Nouvelle Aquitaine")
g.ajouter_arc("Centre - Val de Loire", "Nouvelle Aquitaine")
g.ajouter_arc("Centre - Val de Loire", "Auvergne-Rhône-Alpes")
g.ajouter_arc("Centre - Val de Loire", "Bourgogne-Franche-Comté")
g.ajouter_arc("Bourgogne-Franche-Comté", "Auvergne-Rhône-Alpes")
g.ajouter_arc("Nouvelle Aquitaine", "Auvergne-Rhône-Alpes")
g.ajouter_sommet("Guadeloupe")
g.ajouter_sommet("Martinique")
g.ajouter_sommet("Guyane")
g.ajouter_sommet("Mayotte")
g.ajouter_sommet("La Réunion")
g.ajouter_sommet("Corse")

